### ISSUE TITLE
uptex-fontsで提供するフォントの文字範囲など

### ISSUE THREAD

**Issue by t-tk** [texjporg/uptex-fonts#3]
これまでは、私が2007年に決めた仕様とuptex-fontsの内容は100%同じでした。今後こちらからリリースすることになると思います。当時と状況が変わった点もあり、そうでない点もありますが、当時の話と現在の状況を整理しつつ書いてみようと思います。今後の方針を決めるのに参考になるはずです。

2007年当時の状況

1. UnicodeのBMP外の文字で日本での需要が見込めるめぼしいものは、JIS X 0213の追加漢字の一部(約200字)と「土吉」位(CJK Ideograph Extension B)。Unicode対応ソフトでBMP外(サロゲートペア等)に対応しているソフトはまだ少数派だった。
2. BMP外のためのdviのset3命令は、OmegaやOTFパッケージでも未使用だった。dviwareもovp2ovfなどのツール類もset3未対応。逆にset3があるだけでソフト全体が動かなくなることもあり得る。set3というupTeX専用の機能拡張がどれだけ受け入れてもらえるか不透明。
3. 巨大文字セットはメモリー食い。ディスクに置いておくのもdviware等がメモリーに読み込むのもリソースを食う。フォントの多書体化等の阻害要因にもなる。その割には大規模文字セットを使いたい人はごく少数。

そのため以下の方針にしました。

4. 標準フォント(upjisr-h, upjisg-h, upjisr-v, upjisg-v)はBMP内に限定する。最低限これさえあれば基本的な使用ができる。
5. 日本語のExtension Bは、upjpn{rm,gt}-{h,v}に含めて提供する。必要な人はこちらに切り替えれば upjis{r,g}-{h,v} と上位互換で使えるはず。
6. CKのフォントはCJKサポートの宣伝も兼ねて含める。必要な人以外はdviware等で読み込むことはない。
7. BMP外でサポートするのは漢字だけに限定する。全角のCHARTYPE 0として組まれることになり、TFM(JFM)の拡張が必要無い。

それに対し、現在の状況

8. Unicodeは拡張を繰り返し、CJK Ideograph Extension C~F, 絵文字、変体仮名までBMP外に定義された。日本で需要がありそうで、かつ、(u)pTeX の既存の方法の若干の拡張で需要が満たせそうだがさて。
9. UnicodeのBMP外対応ソフトはありふれてきている。フォントでExtension Bの文字を含むことなどが普通になってきた。おそらくそれらの文字の流通量も増える一方だと見込まれる。
10. upTeXがTeX Liveに入るなど、広く受け入れてもらうことができた。set3対応も大体受け入れてもらえた。上記2の困難はおおむね解消しつつある。ただし、dviout などset3未対応なものも残っている。

今まで、「up(La)TeXはUnicode対応なのにdefaultで「土吉」も出せないの?」みたいな疑問(苦情)が来ているのは承知しています。なので、標準フォントにExtension Bのうちの日本の需要がありそうな約200字を標準フォントに追加するのはありかな、と思いつつ今に至ります。
一方、標準フォントを拡張した場合のデメリットの方も気になっています。
確か、pmostで実現できる多書体がupmpostでは実現出来ないという問題がありました。それが現在どうなっているのか、「set3があるだけでhogeが動かない」というような負の効果はもはや存在しないのか、など気になりつつ調べることができていません。
中韓のフォントの追加については、ディスクに置いておく際のストレージの消費量は少し気になっています。微妙な差異のフォントを何種類も標準の配布に同時に含めるのはデメリットも感じます。新しい方が標準とすべき品質ならば、古い方をobsoleteとしてuptex-fontsの配布から外す、「必要な人はMakefileの方法で作ってね」、と記述しソース配布扱いにする、あるいは現行のものを新しい方に置き換えてしまう(非互換、過激)等の方法もあると思います。

**Comment by aminophen** [comment]
> 「up(La)TeXはUnicode対応なのにdefaultで「土吉」も出せないの?」みたいな疑問(苦情)が来ているのは承知しています。なので、標準フォントにExtension Bのうちの日本の需要がありそうな約200字を標準フォントに追加するのはありかな、と思いつつ今に至ります。

私もこのことは気にかかっていて， texjporg/uplatex#2 という issue を立てていました。「デフォルトで BMP 外が使えない」という状況への改善にはなりませんが，逆に言えば

> 「set3があるだけでhogeが動かない」というような負の効果はもはや存在しないのか

を調べなくて済むというメリットはあると思ったからです。ただ，最近の set3 サポート状況や upmpost の現状を調べておくことは価値がありそうです。

> 中韓のフォントの追加については、ディスクに置いておく際のストレージの消費量は少し気になっています。微妙な差異のフォントを何種類も標準の配布に同時に含めるのはデメリットも感じます。

VF が容量を食うので，微妙な差のものは一つだけにしたいですね。

uptex-fonts の更新にあたっては，「中身を改良したものに従来と同じファイル名をつけて配る」，つまり

> 現行のものを新しい方に置き換えてしまう(非互換、過激)

で良いと思っています。「古い方をobsoleteとしてuptex-fontsの配布から外す」は，TeX Live だけを使うユーザにとっては非互換と大差ないでしょうし，むしろ ZR さんの pxbabel パッケージの改修をややこしくするだけのように思います。

**Comment by t-tk** [comment]
> 「set3があるだけでhogeが動かない」というような負の効果はもはや存在しないのか

正直言って、開発当初はこの心配はすごくしていましたが、upTeXが世間にかなり広まっている現在でもset3を含むdviやvfが爆弾になっている例は聞いていないと思います。
[upTeX で DVI ファイルを作成し，初期設定の状態で dviout で表示しようとすると font file over のエラーが発生し，[OK] をクリックすると dviout が強制終了してしまう ](https://texwiki.texjp.org/?dviout#wadc9abf)という事例がありますが、これもset3が悪いわけではないと思います。
なので、もう忘れてもいいのかな、と思います。万一発生してもツールのメンテナーさんに対策をお願いしたいです。

upmpost の件は、開発初期に「pTeXで出来ることはupTeXでも出来るようにする」という方針で何もかも自力でやろうとしていた頃に解決できず、ToDoに記載したままになっているものです。現状は不明です。
しかし、想定ユーザーさんが非常に少ない機能なので、今やろうとしている upjis{r,g}-{h,v} の文字集合の拡張で症状が悪化することがあるとしても、そのユーザーさんの環境で自力で巻き戻せる情報を提供するだけで良いように思います。

問題の背景としては、Unicodeの拡張とその機能の普及が進むにつれ「Unicode対応」に求める世間の期待が増えかつ多様化する一方、大多数の普通のユーザーさんはその拡張機能を求めていない点、またUnicodeが特定の実装水準を厳しく求めておらず必然的にUnicode対応ソフトの内容がソフト毎にバラバラになっている点が挙げられると思います。
その中で upTeX の default を決めるとともに、より多くを求める人に拡張機能をオプションで提供し、過剰機能が重荷になる人のための軽量化オプションを提供することが出来ればよいのかな、と思います。
そんなこともあり、このトピックスで言えば、

1.  Extension-Bの普及、set3の普及の現状を踏まえ、今後のupTeXの標準フォント upjis{r,g}-{h,v}  は、Extension-B の約200字を含むものにする
2. makejvf に文字集合を決めるオプションを追加し、defaultが過剰もしくは不足なユーザーさんは各自の環境で調整してもらう

という方針を取りたいと思います。
(u)pTeXのエンジン側は、最終的に使われる物理フォントでどんな文字が実装されているかを知りませんし、各ユーザーが必要としている文字集合の大きさも知らないし、Unicodeでは文字集合の実装水準の規定がありません。なのでそこに自由度を許す仕様は合理的です。
そうすると、texjporg/uplatex#2 も自然に解決し、オプション開発・運用コストも減ります。

> uptex-fonts の更新にあたっては，「中身を改良したものに従来と同じファイル名をつけて配る」，
>  現行のものを新しい方に置き換えてしまう(非互換、過激)

はい。そうしたいです。

**Comment by aminophen** [comment]
> Extension-Bの普及、set3の普及の現状を踏まえ、今後のupTeXの標準フォント upjis{r,g}-{h,v} は、Extension-B の約200字を含むものにする

makejvf の `-u custom` が使えるようになったことで、これが技術的に可能となりました。さて、「約200字」というのを具体的にどうすればよいでしょうか。

**Comment by t-tk** [comment]
upjis{r,g}-{h,v} の文字集合として私が考えているのは

- BMP内は従来通り
- BMP外はAdobe-Japan1-6 に含まれている約200字( [Ref.](http://www.tug.org/svn/texlive/trunk/Master/texmf-dist/source/fonts/japanese-otf-uptex/script/sp_list_j.txt?revision=43395&view=markup) )

ただし、cid2code.txt が Unicode-10.0.0 対応で更新されているので、それに伴い追加文字のリストも更新したいと思っています。
逆に、uni{jpn,tch}{rm,gt}-{h,v} は現状では過剰すぎるので、BMP外は Adobe-* に含まれる文字に制限してスリム化したいと思っています。

**Comment by aminophen** [comment]
> 現状では過剰すぎる

仮に upjis を拡大，upjpn を縮小すると，この二つが同一の内容になってしまう気がしますが，両方配る意味はどう考えればよいでしょう？

jsclasses や uplatex や uptex-base は upjis を標準に使っていますし，bxjscls は upjpn を標準に使っているようです。upjis と upjpn の一方を廃止しても影響が出てしまいます。

ちなみに私は

- upjis … BMP内は従来どおり ＋ BMP外の一部を追加（Adobe-Japan1 まで）
- upjpn … BMP内もBMP外も従来どおり（Adobe-Japan1 にとどまらず Unicode の日本語全部入り）

というのを想定していました。

**Comment by t-tk** [comment]
> upjis を拡大，upjpn を縮小すると，この二つが同一の内容になってしまう

それでも良くて、差はなくても upjis と upjpn を両方残す、という案です。
VFのサイズを軽くしたい方向の提案であり、upjpnでAdobe-Japan外の文字を今まで使っていたユーザーさんには負の影響が出ます。

- upjis … BMP内は従来どおり ＋ BMP外の一部を追加（Adobe-Japan1 まで）
- upjpn … BMP内もBMP外も従来どおり（Adobe-Japan1 にとどまらず Unicode の日本語全部入り）

このような考えもあると思います。
現状のルール(Adobe-Japan1で含まれる文字があれば、そのブロック全体は日本語とみなす)では、最近Unicode-10.0.0で追加された変体仮名が upjpn に入りません。upjpnには変体仮名くらいは入れておきたいようにも思います。そうすると、Unicode の日本語全部ってどういうルールで決めればよいか、という疑問が出てきます。
現状のルール + [Scripts.txt](http://www.unicode.org/Public/UNIDATA/Scripts.txt) でいうところの Hiragana, Katakana を入れれば良いのか、もっと更に入れた方がよいのか、…

**Comment by t-tk** [comment]
あともう一点。
従来ルールに従うと、
「Extension F の U+2E569 一字がAdobe-Japan1のCMapに割り当てられたので Extension F全体約7500字を日本語とみなす」という風になります。
このようにUnicodeの改定の度にぶくぶくと VF が巨大化しディスクの肥やしになっていくことは、大多数の普通のユーザーにとって迷惑なだけではないのか??? という疑問を持っています。
Extension B 42,720文字に比べれば小さいとも言えますが、さて。

**Comment by aminophen** [comment]
なるほど，CHARSET をカスタマイズする機能が欲しいと仰っていた理由が見えてきました。

set3 の範囲の文字は，現状の JFM の仕様では TYPE 0 以外に分類できないようになっています。つまり，makejvf が作る VF の最大の目的である「水平シフト」の対象になり得ません。その状況では，単に「ほとんど使わない文字のために VF のファイルサイズだけが肥大化している」という印象は否めませんね。

もう少し悩んでみます。

**Comment by t-tk** [comment]
私が考えていたのは以下の3通り位でした。一長一短あります。

1. CHARSET のようなカスタマイズでスリム化 (上記の案)
2. *.vf.xz を dviware もしくは kpathsea で読み出せるように機能拡張する。
3. VF の仕様自体をCJK Ideographのようなものに対しても効率的に扱えるように拡張し、それに沿って dviware を機能拡張する。

ここで、1. は、手っ取り早くすぐに出来ますが、本質的もしくは最適な解ではなさそうです。
2. は、多少対症療法的な香りですが、ファイルの容量削減という点では抜群の効果が出ます。
3. は、そもそも問題の本質は現状の VF の仕様がCJKの漢字のようなもの(あるいは upTeXでの利用状況)においては非効率的だというところの問題意識から出ています。その点では美しい方針ですが、大袈裟かもしれません。

**Comment by t-tk** [comment]
Extension F の漢字のうち、日本の文字とは? という疑問に対し、[Unicode 10.0
に見る日本の国字](http://kanji.zinbun.kyoto-u.ac.jp/~yasuoka/publications/2017-08-04.pdf) という安岡孝一先生の小論を見つけました。
日本からの提案文字(1645字)が全部「日本の文字」であるとすると、Adobe-Japanに含まれる文字では集合が狭すぎることになります。結局、ルール作りが難しいので、「VF の肥大化は甘受して upjpn でExtension Fは全部追加」が妥当にも思えてきました。

**Comment by aminophen** [comment]
興味深い文献をありがとうございます。仰る通りルールづくりが難しそうですね…

VF を小さくするとどれくらいディスク容量を削減できるのか，と考えてみましたが，upjpn 系のサイズが現在 1.5 MB であることから，uptex-fonts 全体で高々数 MB 〜 十 MB といったところでしょうか。（メモ：tar.xz でダウンロードするので，ネット回線のことはあまり考えなくてよい。）

労力を割くとすれば texjporg/tex-jp-build#8 の

> upTeXでBMP外の文字もプロポーショナルフォントが使えるようにする

つまり JFM フォーマットの拡張の方が重要度が高いと思います。

**Comment by t-tk** [comment]
VFのフォーマットが upTeX にとってサイズの面で非効率的だと思うのは、japanese-otf{,-uptex} の方で特に感じています。
情報量としてさほどでは無いのにも関わらず、japanese-otf の vf が約125MB, japanese-otf-uptex の vf が約88MB
upjpn は可愛い方でした。
今回は、「upjpn では、Extension Fは全部追加」の方向で考えます。
他の「日本の文字」はどうでしょう。変体仮名、携帯電話絵文字のうち文字合成や異体字セレクタなどが不要で一つのコードポイントで表せるもの、などなど、どうしましょうね。

**Comment by t-tk** [comment]
upjpn, uptch は、今のところこちら https://github.com/t-tk/tex-jp-build/commit/e53cb4b552aa5382e43f5d66f4541c64295ec4a4 のuniblock.c を使用する考えです。

**Comment by aminophen** [comment]
> VFのフォーマット

たしかに，otf パッケージの VF は巨大ですね…

簡単そうなのは，TFM → JFM の拡張で行われたのと同様に，「要求されたコードポイントが明言されていな場合は，それが最小の font ID に属し，かつそのコードポイントそのものを出力する」とすればよいのでしょうか。この新フォーマットを仮に「XVF」と呼ぶことにすると，VF と区別できるように id byte を 202 以外の値（さらに PK とかとも被らない値）にすればよさそうです。また，少なくとも「JFM から VF を作る」という makejvf の機構をこれに適合させるのは簡単そうです。otf パッケージの現行版はアドホックに (w)ovp2ovf を使っているわけですが，この際 ZR さんの jfmutil（を XVF 対応化したもの）が使えそうなら移行してもよいかもしれません。あるいは，VF ←→ XVF 相互変換ツールもあるとよい？

問題は，DVIware 側ですね。dvipdfmx と dvips は必須だと思いますが，その内部に「VF ←→ XVF 変換コード」を追加すれば案外簡単だったりしないかな？

> upjpn, uptch

了解です。

**Comment by aminophen** [comment]
現時点で存在する「ファイル冒頭の id byte（＝ 最初のバイト 249 の後に続くもの）」の値：

* id = 2: DVI
* id = 7: XDV (xetex.web in TeX Live 2017) ← XeTeX は昔 4, 5, 6 だった頃もあった。3 は right-to-left と left-to-right の混在する拡張フォーマットで使われるという言及があるが詳細は不明
* id = 89: PK (pktype.web)
* id = 131: GF (gftype.web)
* id = 202: VF (vftovp.web) ← OVF (ovf2ovp.web) もそのまま
* id = 319: PKD ('p'+'k'+'d'; chkfont.c in DVIOUT) ← DVIOUT 独自と思われる

フォントの id 値ってどうやって決まっているのだろう…？

**Comment by aminophen** [comment]
もっとファイルを小さく(*1)しようとすると，文字を JFM のようにタイプ分けすればいいのでしょうが，これは普通の VF で使われている言語体系（DVI 命令と共通）で表せない可能性が高いので，DVIware の改修が大変そうです。

(*1) 例えば漢字と仮名のフォントを分ける makejvf -K とかを想定；漢字もたくさん・仮名もたくさんなので，上述の XVF ではサイズ半減程度にすぎない可能性が高い。

otf パッケージの VF をよく知らないのですが，どこまで拡張すれば小さくできそうなのでしょう？

**Comment by t-tk** [comment]
> 簡単そうなのは，TFM → JFM の拡張で行われたのと同様に，「要求されたコードポイントが明言されていな場合は，それが最小の font ID に属し，かつそのコードポイントそのものを出力する」とすればよいのでしょうか。

私は、この案がいいように思います。
欧文TeXやOmegaなどのVFの動作と区別する必要があるとするならば、若干条件を追加して、
「MAPFONTで指示されているfont IDの一番若いものがJFMであるとき、要求されたコードポイントが明言されていな場合は，それが最小の font ID に属し，かつそのコードポイントそのものを出力する」
というルールの追加でよいように思います。つまり、VFの仕様拡張としては、idを追加して新しい命令を用意して…という方向でなく、解釈を拡張するというイメージです。

例えば、現状、upphiraminw3-h.ovp は、冒頭が
```
(MAPFONT D 1
   (FONTNAME uphminr-h)
   (FONTCHECKSUM O 0)
   (FONTAT R 1.000000)
   (FONTDSIZE R 10.000000)
   )
```
で、おしまいの方に次のようなエントリーが延々と続きます。
```
(CHARACTER H 2F9F4
   (CHARWD R 1.000000)
   (MAP
      (SETCHAR H 2F9F4)
      )
   )
```

その代わり、CHARACTERのエントリーがない文字コード 0xXXXXX の要求が来た場合、従来エラーでしたがその代わりに
```
(CHARACTER H XXXXX
   (CHARWD R 1.000000)
   (MAP
      (SETCHAR H XXXXX)
      )
   )
```
であると解釈する、という新ルールです。

otf パッケージでは、現在 {,u}mkjvf によりovp を生成しています。該当部分を削除すれば済むだけですので、改造は容易でしょう。
逆に出力不能な文字がソースに来た場合、従来は{,u}platexのコンパイル時にエラーが出ましたが、新ルールの元ではdviwareの処理までエラーが出ないことになります。

> 問題は，DVIware 側ですね。dvipdfmx と dvips は必須だと思いますが，その内部に「VF ←→ XVF 変換コード」を追加すれば案外簡単だったりしないかな？

これが敷居が高いところだと思います。実際やってみるとそれ自体は出来るかもしれませんが、現在非推奨とされているdviware (dviout, xdviなどなど) 全てまでとなると手が回るのかどうか心配です。「非推奨のdviwareを使用する人は従来形式のvfを別途用意して使ってください」のような方法もなくはないですが。

> もっとファイルを小さく(*1)しようとすると

漢字のエントリーが圧縮できれば私の意図としては効果充分です。

**Comment by t-tk** [comment]
考え違いをしていたかもしれません。
upphiraminw3-h.vf の該当部分(容量を食っている部分)を読むのは dviware ではなくて、{,u}pTeX エンジンでしたっけ?
そうならば、改造は {,u}pTeX エンジンだけで済みます。

**Comment by aminophen** [comment]
> 「MAPFONTで指示されているfont IDの一番若いものがJFMであるとき、要求されたコードポイントが明言されていな場合は，それが最小の font ID に属し，かつそのコードポイントそのものを出力する」
> というルールの追加でよいように思います。つまり、VFの仕様拡張としては、idを追加して新しい命令を用意して…という方向でなく、解釈を拡張するというイメージです。

なるほど、これはいいかもしれません。

> upphiraminw3-h.vf の該当部分(容量を食っている部分)を読むのは dviware ではなくて、{,u}pTeX エンジンでしたっけ?

よく知りませんが、VF を *TeX が読むことはなかったような？

**Comment by aminophen** [comment]
今まで和文の JFM/VF を正常に扱えていたものは，以下のものでよろしいでしょうか。

- **dvipdfmx**
- **dvips**
- **dvisvgm**
- dviout
- pxdvi

dvipng は TeX Wiki によると日本語の扱いは「サブフォント機構を使って作成した dvi」しか対応していないらしいので，pTeX 系の普通の DVI はダメなはずです。（ほかにも dviware はありますが，dvitype や dvi2tty や seetexk のものなどは VF を読まないので関係ないはず。）

dvipdfmx と dvips くらいはネイティブに新しい VF に対応化させたほうがよいのでしょうが，他も個別にとなると面倒です。そこで，もしかして…？と思いついたのが「dvicopy の pTeX 対応化」です。

dvicopy は「VF を展開して DVI に直接その情報を埋め込むもの」と私は認識していますが，残念ながら pTeX の JFM を使った DVI を dvicopy に食わせると Bad TFM file のエラーになります。Omega 版の odvicopy も pTeX の JFM を読めません。もし pdvicopy を作れたなら，そしてそれが新しい VF も展開してくれたなら，workaround の選択肢は広がるかもしれません。（tex4ht も確か NTT JTeX しかダメだったので，その辺も対応できるかも，とか想像は広がる。）

**Comment by t-tk** [comment]
> 今まで和文の JFM/VF を正常に扱えていたものは，以下のものでよろしいでしょうか。

> - **dvipdfmx**
> - **dvips**
> - **dvisvgm**
> - dviout
> - pxdvi

ぱっと思いつくのはそれだけです。
 [xgdvi ](http://www-masu.ist.osaka-u.ac.jp/~kakugawa/TeX-Guy/)も「仮想フォント対応」とのことでotfパッケージの一部くらいは動くのかもしれませんが、今回の件で動かなくなったとしてもやむを得ないと思います。
Mxdvi は、otfパッケージのマニュアルに動作すると記載されている dviware ですが、開発停止状態のようです。
もっとマイナーなものもあるのかもしれません。

> dvicopy

なるほど。ただし、私にはソースを覗いて改良して…という元気が出ません。済みません。

**Comment by aminophen** [comment]
@t-tk さんのコメント

> VFのフォーマットが upTeX にとってサイズの面で非効率的だと思うのは、japanese-otf{,-uptex} の方で特に感じています。情報量としてさほどでは無いのにも関わらず、japanese-otf の vf が約125MB, japanese-otf-uptex の vf が約88MB

を見て，改めて japanese-otf(-uptex) を見てみると `{p,up}phira{min,kaku,maru}*.vf` の存在が気になりました。これはヒラギノフォント専用の \propshape ですよね？

「non-free なパッケージを分けて欲しい」というのは以前 Karl さんから要望を受けて，ひとまずは texjporg/jfontmaps#1 にあるとおり了承を得ています。ところが，ヒラギノフォント専用の VF が結構容量を食っているという状況を見ると，japanese-otf(-uptex) のヒラギノ VF は，TeX Live から外して tlcontrib へ移す方が良い気がします。

＃ VF のフォーマット拡張あるいは解釈の拡張という案はちょっとやる気が出ていません…

**Comment by t-tk** [comment]
確かに  `{p,up}phira{min,kaku,maru}*.vf`  はヒラギノ専用かつプロポーショナル仮名でしか使われず汎用性が低いという観点から、一般向けのCTANもしくはTeX Liveの配布からは外す方針案は理解できます。
もしそうするなら、ヒラギノのプロポーショナル仮名を使いたい場合のvfの入手法を説明しておけばよいのでしょう。
齋藤さんの一次配布はソースのみかつTeX Liveに含まれるツールで全てのvfが作成可能なので、「それを元にvfを作ってください」でも問題ないはずです。(少々不親切ですが)

[tlcontrib](https://git.texlive.info/tlcontrib/) というものが出来たのですね。初めて知りました。
開発者の場合の使い方、一般ユーザーの使い方など、どこかに解説が出ているのでしょうか?

**Comment by aminophen** [comment]
> tlcontrib というものが出来たのですね。初めて知りました。
> 開発者の場合の使い方、一般ユーザーの使い方など、どこかに解説が出ているのでしょうか?

tlcontrib は結構前から（[2010年ごろ？](http://tlcontrib.metatex.org)）からあったようですが，更新が止まってしまって[最近ノルベルトさんが引き継いだ](https://www.preining.info/blog/2017/07/tlcontrib-renewed/)のだと思います。

一般ユーザの使い方は，texjp.org の下にある tltexjp の使い方と同じです (tlmgr repository add) 。

開発者の場合も，運用上は tltexjp と同じような状態でしょう。（tlcontrib の場合は，CTAN に nonfree なパッケージが上がったらノルベルトさんが取り込んでサーバーにあげる。tltexjp の場合は，GitHub に更新があったらノルベルトさんが取り込んでサーバーにあげる。）

今のところ，hiraprop と cjk-gs-integrate.macos と ptex-fontmaps.macos が tlcontrib のコンセプトに合っているので，tlcontrib 行きの候補になると思います。pxdvi / ptex-ng バイナリは tltexjp で今後も配布することを考えています。

**Comment by aminophen** [comment]
VF の解釈の拡張について改めて考えていますが，

> 「MAPFONTで指示されているfont IDの一番若いものがJFMであるとき、要求されたコードポイントが明言されていな場合は，それが最小の font ID に属し，かつそのコードポイントそのものを出力する」

を実現するには，VF の作成過程のどこかで「VF で明言しないべきコードポイント」を特定する必要があり，これをどのプログラムが担うかでかなり難易度が変わりそうです。

まず，現状日本で使われている VF 生成プログラムを見てみると，以下のような感じでした。

* makejvf（デフォルトの pTeX / upTeX フォントはこれ）
    - JFM を利用するので，「明示しないべきコードポイント」の特定が比較的簡単に実現できそう。ただし，ルーチンは大幅に書き換えないといけないように見える。
* ovp2ovf / wovp2ovf（OTF パッケージはこれ）
    - これは「OVP を読み込んで全部の文字情報を格納した後，それが完全一致するものを数え上げて，最大数のものを特定する」という処理が必要になるので難しそう
    - （つい先ほどの texjporg/tex-jp-build#42 は，この実現可能性を確認している時に気づきました。）

別の方法として考えられるのが

* 新たに「従来の全文字コードを含む VF」と「明示しない文字コードを省いた VF」を相互変換するプログラムを作成し，makejvf や (w)ovp2ovf で作った大きな VF を縮小する。

ですが，これもやはり「完全一致するものを数え上げて，最大数のものを特定する」が必要になるので，難易度としては大差ないように思います。

もう少し手軽かつ汎用的な方法を考えないと，なかなかに難しそうです…

（一案として，OTF パッケージの VF の元になる OVP に吐き出す文字を削る？）

**Comment by t-tk** [comment]
VFの解釈の変更のご検討ありがとうございます。

>（一案として，OTF パッケージの VF の元になる OVP に吐き出す文字を削る？）

これが有力と思います。元々スクリプトで生成しているOVPなので、そこに手を入れるのが分かりやすいと思います。

とりあえず、それは次の課題として、ぼちぼち今までのところをまとめて一度リリースしたいと思っています。しばらくサボっていましたがTeX Live 2018に余裕で間に合うようにしたいです。
upjisのBMP超えのコードポイント追加を試しに作ってみました→ https://github.com/texjporg/uptex-fonts/commit/93d5bfdc1021215a993479a3e0f615ad95a93da2

**Comment by zr-tex8r** [comment]
本題とはあまり関係ないのですが：

>   MAPFONTで指示されているfont IDの一番若いもの

「VFのchar packatのDVIコードにおけるフォントの初期値」がそれになるんでしたっけ？

**Comment by aminophen** [comment]
vptovf.web によると

> (If no other font is selected, font
> number~0 is the default. If no \.{MAP} attribute is given, the default map
> is a character of the same number in the default font.)

なので，初期値は 0 なのが厳密な VF だと思われます。しかし実際には 0 が定義されていなくて 1 から始まる VF があるので，その場合の仕様はよくわかりません。

**Comment by zr-tex8r** [comment]
「あまり関係ない」こともないですね。ttkさんの書いた擬似コード

```text
(CHARACTER H XXXXX
   (CHARWD R 1.000000)
   (MAP
      (SETCHAR H XXXXX)
      )
   )
```

を素直に解釈すると「初期値のフォント」が使われるはずです。私自身、“暗黙の”文字については「初期値のフォント」が使われるのが自然だと考えています。だからもし「初期値のフォント」が「ID最小のフォント」と食い違うのであれば、何れを採るべきか検討すべきかと思います。

**Comment by zr-tex8r** [comment]
以下は実際のソフトウェアで調べてみた結果です。

  * vptovfは`MAPFONT`の番号を0からの連番に振りなおす。この場合、`MAP`中の`SELECTFONT`の番号も連動して変わる。
    （そういえば昔、ofmtoolsで「`SELECTFONT`の番号の連動を忘れている」というバグがあったような。）
    従って、vptovfで生成した.vfでは、fnt_defのidは常に0からの連番になる。
  * といっても、idが0からの連番でない.vfを作ることもできるわけで、その場合「初期値のフォント」は何になるか。
      * dvips／dvipdfmx／pdfTeX／LuaTeXでは、一番最初に現れるfnt_defになる。
      * dvioutでは、idが0のfnt_defになる。（存在しない場合はクラッシュする。）
  * つまり、「先頭のfnt_defのidが0でない」場合の解釈は定まっていない。

**Comment by aminophen** [comment]
> 解釈は定まっていない

は確かですが，t-tk さんのコメントの「MAPFONTで指示されているfont IDの一番若いもの」を「初期値のフォント」と同義のものとして読み替えれば，特に問題になる話ではないと思います。

というのも，以下の2点が真である状況ならば，両者は同義であることが導けると思います。

- VF を解釈するプログラムが「一番最初に現れる fnt_def」を「初期値のフォント」としている。
- 実際に pTeX 系列で使われている日本語の VF はおそらくすべて「一番最初に現れる fnt_def」は「ID が最小」である。

実装上も，「ID の一番若いもの」というルーチンを新たに追加することは多分なく，「初期値のフォント」にフォールバックさせるでしょうから，問題はないと思います。

**Comment by aminophen** [comment]
ところで試していなくて恐縮ですが，「dviout が id 0 の fnt_def が存在しない場合はクラッシュ」という問題って，まだ直っていないんでしたっけ？ 前にその挙動は forum でも問題になっていた記憶があるのですが，（makejvf の -i オプションを実装して当面は回避しつつも）dviout 本体でも fix されたのだろうとばかり思っていました。

**Comment by zr-tex8r** [comment]
>   特に問題になる話ではないと思います。

はい、「どっちかに決めて」混同しなければ問題ない話だと思います。

>   dviout 本体でも fix されたのだろうとばかり思っていました。

自分の記憶でもそうなんですが、実際にTeX Live2017のdvioutで試したらあっけなくクラッシュしました。もしかしたら「特定のパターンだけ回避した」みたいなことなのかも知れません。

※`MAPFONT`2つで色々なidのパターンを試したのですが、一貫して「0があればそれが使われ、0がないとクラッシュ」という結果でした。

**Comment by t-tk** [comment]
makejvf/uniblock.c の更新 (Blocks-10.0.0.txt対応) は TeX Live svn にコミットしました。([r46299](http://www.tug.org/svn/texlive?view=revision&revision=46299), https://github.com/texjporg/tex-jp-build/commit/4e25b34a86b14dc797c2b594bb8917538ea2777f)
以下の4個の文字は、最近のUniJIS-UTF16-* に追加されたものですが、おそらく(upTeXでUTF-8で直に入力するという)需要がないので無視することにしました。
 
*  U+0FD6   ࿖   Left-facing Svasti Sign   CID:12182 in Tibetan block
*  U+2E40   ⹀   Double Hyphen         CID:15516 in Supplemental Puncutuation block
*  U+A7B5   ꞵ   Latin Small Letter Beta   CID:15909 in Latin Extended-D block
*  U+AB53   ꭓ   Latin Small Letter Chi    CID:15911 in Latin Extended-E

uptex-fonts の更新は、upjpn, upjis については https://github.com/texjporg/uptex-fonts/commit/ea73414af4932b3fe2a73a91c700bbcbc5e86a6a の状況のものでfixしようと思っています。そろそろ master にマージするつもりです。→ マージしました。 https://github.com/texjporg/uptex-fonts/commit/e516586b3e74e4eb3c4a28792cef9c85d1a3b313

リリースに向けて作業は何が残っているでしょうか?

* 中国語の約物の更新のfix
* tfm, vfの再生成、更新  (→完了 https://github.com/texjporg/uptex-fonts/commit/975510cd34e3ce0b59524282c36a2b9dadb6fc73)
* changelog を追加更新
* CTAN 登録

といったところでしょうか。

**Comment by aminophen** [comment]
ありがとうございます。テストしてみたくなったので make してみました (975510c) 。

**Comment by t-tk** [comment]
しばらく経ってしまいました。
私の触った部分 upjpn, upjis については生成していただいた tfm, vf を含めリリースOKと思っています。
中国語の部分はどうしましょう。
もうそろそろリリースしませんか?

**Comment by aminophen** [comment]
中国語も ok だと思いますので，リリースしましょう。

メモ：japanese-otf-uptex にも，今回の upjis* と等価な設定を追加しても良いのではないかと思っています。記憶にある範囲では，具体的には U+00B7 が該当します。
