### ISSUE TITLE
U+301Eの縦組み字形

### ISSUE THREAD

**Issue by t-tk** [texjporg/uptex-fonts#7]
記事を見かけたのでここにも話題に挙げておきます。
[U+301Eの縦組みが変だ](https://togetter.com/li/691637)

繁体字中国語フォントでは、まともに配置される方が普通。
日本語では游明朝/游ゴシック、Source Han Sans JP がまともだそうです。

upjisr-{v,h}.pl などの char_type 2 に U+301E を追加した方が良いかもしれません。

**Comment by aminophen** [comment]
まだよくわかっていませんが，「U+301E に対応する JIS code はないが，中国語では割り当てられている」という話があるのですね。

デフォルトで char_type 2 に追加するかどうかはまだ考えていませんが，誰かがそのような JFM を作成する可能性を考慮し，r46657 で makejvf の writevfu() 関数に U+301E を追加しておきました。

**Comment by t-tk** [comment]
横組に関しては、Adobe-GB, Adobe-CNSともにU+301D, U+301E の組がありました。
U+301D:  GB CID9990, CNS CID170
U+301E:  GB CID9991, CNS CID171
uptex-fonts の中国語フォントに横組の閉じ括弧としてU+301Eを追加した方が良さそうです。
しかし、縦組み字形は見つけられませんでした。

参考: [Unicode Vertical Text Layout @ unicode.org](http://www.unicode.org/reports/tr50/)
今回の話題に関連するところでは、
そこの[#brackets](http://www.unicode.org/reports/tr50/#brackets) で、かつCJKで使うものは全部 uptex-fonts で扱えるようにすれば良いような気がしますが、全容が把握できていません。
[#vertical_alternates](http://www.unicode.org/reports/tr50/#vertical_alternates) も気になります。

**Comment by t-tk** [comment]
https://github.com/texjporg/uptex-fonts/issues/6 の方で括弧類全般を話題に出していますが、DOUBLE PRIME QUOTATION MARK 関係はこちらで話をまとめることにします。

https://github.com/texjporg/uptex-fonts/blob/guillemet/source/punctuation.md から表を抜粋。

|Unicode |   |width|gc|vo|JIS X 0213|UniJIS-*-H| -V | upjis*.pl |
|--------|:-:|:-:|:-:|:-:|----------|:-----:|:-----:|:-----:|
| U+301D | 〝 |W|Ps|Tr| 1-13-64  | 7608  | 7956  | type1 |
| U+301E | 〞 |W|Pe|Tr| NA       | 12170 |(12170)| NA    |
| U+301F | 〟 |W|Pe|Tr| 1-13-65  | 7609  | 7957  | type2 |

|Unicode |  |width|gc|vo| GBK2K |UniGB-*-H| -V | upsch*.pl |
|--------|:-:|:-:|:-:|:-:|----------|:-----:|:-----:|:-----:|
| U+301D | 〝 |W|Ps|Tr| a894     | 9990  |(9990) | type1 |
| U+301E | 〞 |W|Pe|Tr| a895     | 9991  |(9991) | NA    |
| U+301F | 〟 |W|Pe|Tr| NA       | NA    | NA    | type2 |

|Unicode |  |width|gc|vo| B5    |UniCNS-*-H| -V | uptch*.pl |
|--------|:-:|:-:|:-:|:-:|-----|:-----:|:-----:|:-----:|
| U+301D | 〝 |W|Ps|Tr| a1a9  | 170   |(170)  | type1 |
| U+301E | 〞 |W|Pe|Tr| a1aa  | 171   |(171)  | NA    |
| U+301F | 〟 |W|Pe|Tr| NA    | NA    | NA    | type2 |

* Adobe-Japan1では、U+301Eの縦組みにCID7957を割り当て、U+301Eをtype2にすれば、(U+301D, U+301E)のセットを縦横ともに正しく組めるようになる。
* Adobe-CNS1, Adobe-GB1 ともに (U+301D, U+301E) の組が存在し、U+301F は存在しない。
* Adobe-Korea1 では CID9322が U+301E, CID9323が U+301F ということになっているが、CID9322がopen, CID9323がcloseのように見える。Unicodeの"General Category Value"との対応関係がしっくりこない。U+301E(CID9322)をtype1(Ps相当), U+301F(CID9323)をtype2(Pe相当)とすれば、Adobe-Korea1に対してはそれっぽく組めそうだが場当たり感が否めない。その上これらはUHCのようなメジャーなレガシーエンコーディングには含まれていない。

以上の状況から、以下のようにしようと思います。

* upjpn(upjis), upsch, uptch には、U+301Eをtype2として追加する
* upkor から U+301D type1, U+301F type2 の割り当てを削除し、upkorでの対応は無しとする。
* UniJISup-UTF16-V に U+301E CID7957 の対応を追加する。

さらに、upsch, uptch からU+301Fのtype2の割り当てを削除しても大丈夫そうですが、あっても害はないはずなので、そのままにしようかと思います。

**Comment by t-tk** [comment]
U+301Eはサンプル https://github.com/texjporg/uptex-base/commit/b4619780f1f6872c613b726a2b2542613a5e150b で上手く動いているので、こちらは閉じます。
リリースなどの話は #6 の方でします。

**Comment by t-tk** [comment]
https://github.com/texjporg/uptex-fonts/issues/7#issuecomment-369592392 の表を更新内容に合わせて書き直しておきます。
|Unicode |   |width|gc|vo|JIS X 0213|UniJIS-*-H| -V | UniJISup-*-V | upjis*.pl |
|--------|:-:|:-:|:-:|:-:|----------|:-----:|:-----:|:-----:|:-----:|
| U+301D | 〝 |W|Ps|Tr| 1-13-64  | 7608  | 7956  | 7956 | type1 |
| U+301E | 〞 |W|Pe|Tr| NA       | 12170 |(12170)| 7957 | type2 |
| U+301F | 〟 |W|Pe|Tr| 1-13-65  | 7609  | 7957  | 7957 | type2 |

|Unicode |  |width|gc|vo| GBK2K |UniGB-*-H| -V | upsch*.pl |
|--------|:-:|:-:|:-:|:-:|----------|:-----:|:-----:|:-----:|
| U+301D | 〝 |W|Ps|Tr| a894     | 9990  |(9990) | type1 |
| U+301E | 〞 |W|Pe|Tr| a895     | 9991  |(9991) | type2 |
| U+301F | 〟 |W|Pe|Tr| NA       | NA    | NA    | type2 |

|Unicode |  |width|gc|vo| B5    |UniCNS-*-H| -V | uptch*.pl |
|--------|:-:|:-:|:-:|:-:|-----|:-----:|:-----:|:-----:|
| U+301D | 〝 |W|Ps|Tr| a1a9  | 170   |(170)  | type1 |
| U+301E | 〞 |W|Pe|Tr| a1aa  | 171   |(171)  | type2 |
| U+301F | 〟 |W|Pe|Tr| NA    | NA    | NA    | type2 |
