### ISSUE TITLE
UniJIS{,2004}up-UTF16-{H,V} の更新

### ISSUE THREAD

**Issue by aminophen** [texjporg/uptex-fonts#8]
#5 の時に作った新しい CMap ですが，まだ Adobe-Japan1-7（新元号の CID 追加）に対応していないので，追随したいと思います。それに関連して：

- Adobe の元の CMap から「up 版」を自動で生成するスクリプトがあれば嬉しいです（が，これを書くのは私には手に負えないと思います…）。
- ptex-fontmaps の kanji-config-updmap(-sys) で「up 版」を選択できるインターフェースがあれば良いかもしれません。そのためには，元の updmap.pl 及び設定ファイル updmap.cfg を拡張する必要があると思いますが，考えてみます。

**Comment by norbusan** [comment]
@aminophen `updmap.pl`について、`ptex-fontmaps`のgitに`tl-updates/updmap.pl`が入って、いろな更新があります。
後少し2019版のテスティングが始まりますから、今のところの`tl-updates/updmap.pl`とうえの更新を作成しましょう！
現在のtlnetに入れてほしかったら、早くしないといけません。

**Comment by aminophen** [comment]
> ptex-fontmapsのgitにtl-updates/updmap.plが入って、いろな更新があります。

確認しました。更新の中身は texjporg/jfontmaps#10 のための program-specific embed settings ですね。すっかり忘れていました。まだ細かい仕様が決まっていませんから，2018 版の tlnet には入れなくていいです。2019 版の tlnet を目標にします。

**Comment by norbusan** [comment]
了解です！僕もすっかり忘れて、昨日あの`updmap.pl`再発見しました（笑）。ありがとうございます。

**Comment by t-tk** [comment]
- Adobe の元の CMap から「up 版」を自動で生成するスクリプトがあれば

当初作ろうと考えていましたが、更新頻度もさして多くないのでどっちが楽か分からないので自動化はしなかったと記憶しています。(きちんと作業履歴をたどる必要があります。)

Adobe-Japan1-7 への追従は、私がやるつもりでした。もう少々おまちいただければ。

**Comment by t-tk** [comment]
#5 全角コロンの縦組み字形に関連する話で、さっき気付いたのですが
UniJIS-UTF16-V, UniJIS2004-UTF16-V の2018年7月の版で縦組み字形が5個追加されていました。
追加されたのは U+337B..337E (平成、昭和、大正、明治の縦組み字形), U+FF1A (全角コロン) です。
この変更について cid2code.txt のコメント部分には反映されていないようで、
よく理解できない旨を投稿しました。https://github.com/adobe-type-tools/cmap-resources/issues/8

以前から UniJIS{,2004}up-UTF16-V で独自対応していた内容と同等になります。(なので方針変更も必要なし)
UniJIS{,2004}up-UTF16-V を使わずともオリジナルの UniJIS{,2004}-UTF16-V で全角コロンの縦組み対応が実現したことになります。

**Comment by aminophen** [comment]
> UniJIS-UTF16-V, UniJIS2004-UTF16-V の2018年7月の版で縦組み字形が5個追加されていました。

全角コロンの縦組対応とは…😃 一歩前進ですね。気づいていませんでした，ありがとうございます。

**Comment by t-tk** [comment]
cmap-customize というブランチ https://github.com/texjporg/uptex-fonts/tree/cmap-customize に置きました。
テストして問題なさそうでしたら 2/9(土) 頃にCTANへリリースしようと思います。
ついでに UTF8-UTF16 の Unicode 11.0.0 対応も入れています。

cid2code.txt のコメントの件も @kenlunde さんが早速修正してくださいました。対応速い!

**Comment by t-tk** [comment]
組版に影響を与える話ではありませんが
CTAN の adobemapping に関し、上記 cid2code.txt の更新の他に
COPYRIGHT 表記の更新 (Adobe Sys­tems In­cor­po­rated → Adobe) が入り版数も上がっていました。
コードの中身自体は2018年7月の版から変更は無いようです。

**Comment by kenlunde** [comment]
> コードの中身自体は2018年7月の版から変更は無いようです。

そうです。

**Comment by aminophen** [comment]
> COPYRIGHT 表記の更新 (Adobe Sys­tems In­cor­po­rated → Adobe) が入り版数も上がっていました。

昨日の cid2code.txt の修正に git tag が付くタイミングを待って，CTAN / TeX Live に取り入れようと思います。

**Comment by kenlunde** [comment]
[February 5, 2019 Release](https://github.com/adobe-type-tools/cmap-resources/releases/tag/20190205)

**Comment by aminophen** [comment]
@kenlunde ありがとうございます！

今夜，CTAN の adobemapping を更新します。

**Comment by aminophen** [comment]
CTAN に新しい adobemapping を登録しました。

**Comment by t-tk** [comment]
CTAN に uptex-fonts 2019-02-09版を投稿しました。
まだ↓の話題が残っていると思います。ここで続けるか、ここを閉じて別のIssueで続けるかはおまかせします。
> - ptex-fontmaps の kanji-config-updmap(-sys) で「up 版」を選択できるインターフェースがあれば良いかもしれません。

CMapの作り方について備忘録を以下に書いておきます。(自分でも忘れてしまうので)

今回も生成スクリプトの類は作成していない。
以下が差分の小さい組み合わせなので、それを手で編集。

* UniJIS-UTF16-H → UniJISup-UTF16-H  (4個入れ替え)
* UniJIS2004-UTF16-H → UniJIS2004up-UTF16-H  (4個入れ替え)
* UniJIS-UTF16-V → UniJISup-UTF16-V  (9個追加と begincidchar-endcidcharの範囲調整)
* UniJIS2004-UTF16-V → UniJIS2004up-UTF16-V  (9個追加と begincidchar-endcidcharの範囲調整)

あとはコメント等の編集。

**Comment by aminophen** [comment]
ありがとうございます！

> * ptex-fontmaps の kanji-config-updmap(-sys) で「up 版」を選択できるインターフェース

https://github.com/texjporg/jfontmaps/issues/16 に移行することにして，こちらは閉じます。

**Comment by aminophen** [comment]
2019-07-30 付け cmap-resources で以下のファイルが更新されています。

* Adobe-Japan1-7/CMap/UniJIS-UTF16-H
* Adobe-Japan1-7/CMap/UniJIS-UTF32-H
* Adobe-Japan1-7/CMap/UniJIS-UTF8-H
* Adobe-Japan1-7/CMap/UniJIS2004-UTF16-H
* Adobe-Japan1-7/CMap/UniJIS2004-UTF32-H
* Adobe-Japan1-7/CMap/UniJIS2004-UTF8-H
* Adobe-Japan1-7/CMap/UniJISX0213-UTF32-H
* Adobe-Japan1-7/CMap/UniJISX02132004-UTF32-H
* Adobe-Japan1-7/cid2code.txt

**Comment by t-tk** [comment]
すっかり忘れていました。TeX Live 2020に間に合わせたいと思います。
AJの更新内容は[ここ](https://github.com/adobe-type-tools/cmap-resources/releases/tag/20190730)に記載されていました。

Unicode | CID
-- | --
U+02C9 | 129
U+02CA | 127
U+02CB | 65
U+030D | 15846
U+29C8 | 12232
U+2B97 | 12180
U+1F79C | 12244

U+2B97 は Unicode 13.0 に登録予定とのこと。

UTF8-UTF16 と同時に更新しようと思います。
CTANに入ればいいので 3月22日に間に合うように作業します。

**Comment by t-tk** [comment]
CMapの作り方について備忘録。(自分でも忘れてしまうので)

今回も生成スクリプトの類は作成していない。
以下が差分の小さい組み合わせなので、それを手で編集。

* UniJIS-UTF16-H → UniJISup-UTF16-H  (4個入れ替え)
* UniJIS2004-UTF16-H → UniJIS2004up-UTF16-H  (4個入れ替え)

あとはコメント等の編集。XUIDの削除。
今回は縦組み字形のレパートリーに変化が無いので`-V`は更新なし。以下の作業はしていない。

* UniJIS-UTF16-V → UniJISup-UTF16-V  (9個追加と begincidchar-endcidcharの範囲調整)
* UniJIS2004-UTF16-V → UniJIS2004up-UTF16-V  (9個追加と begincidchar-endcidcharの範囲調整)

**Comment by t-tk** [comment]
[2020-02-29](https://github.com/texjporg/uptex-fonts/releases/tag/2020-02-29) としてリリースしました。
後ほどCTANに投稿します。
ここは閉じます。

**Comment by t-tk** [comment]
[小書き仮名「こ」「コ」](https://github.com/t-tk/japanese-otf-uptex/issues/6) を追加します。

upstream で追加する動きが見えないので先行して追加します。
https://github.com/adobe-type-tools/cmap-resources/issues/12

**Comment by aminophen** [comment]
上流の adobemapping が更新されたので https://github.com/aminophen/ctan-adobemapping で取り込んで CTAN に登録しました。明日には TeX Live にも反映されると思います。

**Comment by t-tk** [comment]
adobemapping の更新情報、ありがとうございます。
https://github.com/texjporg/uptex-fonts/commit/ada2edc64aada1544ad970c13ab49b2b6c8e5e51 で反映させました。
手元でテストしたところ期待通りに動いているようです。
週末にCTANに投稿します。

**Comment by t-tk** [comment]
テストファイルを samples/* に追加しました。これは、CTAN投稿のアーカイブには含めず、ここだけの管理にします。
CTANに投稿しました。ここは閉じます。
