### ISSUE TITLE
Installing uptex-fonts in TeXLive

### ISSUE THREAD

**Issue by dmurdoch** [texjporg/uptex-fonts#9]
I cloned `uptex-fonts` and ran `make; make install`.  It appears the fonts were correctly installed, but `dvipdfmx` from TeXLive still isn't finding them.  I'm not a TeX expert, so giving installation instructions would be really helpful.

**Comment by munepi** [comment]
If you are not a TeX expert, you do not need to clone/build/install the repository `uptex-fonts`. 

The package `collection-langjapanese` supports all Japanese (u)pTeX/(u)pLaTeX packages, including `uptex-fonts`. 
You can install `collection-langjapanese` on your TeX Live environment below. 

```
$ sudo tlmgr install collection-langjapanese
```

**Comment by dmurdoch** [comment]
Thanks!  That solved my problem.  Perhaps a note about this could be added to the README for this repository?
